import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import './globals.css'
import {ReduxProviders} from "../redux/Provider";
import {OAuthProvider} from "../services/lichess/OAuthProvider";

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <OAuthProvider>
        <ReduxProviders>
            <html lang="en">
            <body className={inter.className}>{children}</body>
            </html>
        </ReduxProviders>
        </OAuthProvider>
    )
}
