import type {Metadata} from 'next'
import {Lato} from 'next/font/google'
import './globals.css'
import {ReduxProviders} from "../redux/Provider";
import {OAuthProvider} from "../services/lichess/OAuthProvider";

const lato = Lato({
    weight: ['400', '700'],
    style: ['normal', 'italic'],
    subsets: ['latin'],
    display: 'swap',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <OAuthProvider>
        <ReduxProviders>
            <html lang="en" className={lato.className}>
            <body>{children}</body>
            </html>
        </ReduxProviders>
        </OAuthProvider>
    )
}
